staging-settings:
  rpcs:
    - chain-name: monad-testnet
      url: https://rpc-testnet.monadinfra.com

fixture-execute-settings:
  rpcs:
    - chain-name: monad-testnet
      url: https://rpc-testnet.monadinfra.com

live-lifecycle-wait-settings:
  rpcs:
    - chain-name: monad-testnet
      url: https://rpc-testnet.monadinfra.com
